### ISSUE TITLE
Links dos projetos(Link e Repositório)

### ISSUE THREAD

**Issue by Diego-Girao** [luissshc29/portfolio#1]
Todos estão abrindo o projeto/repositório sobrepondo o seu portfólio, quando o "correto" seria ele abrir em uma nova aba, assim o usuário poderá ver seus projetos e continuar no seu portfólio.

**Comment by luissshc29** [comment]
Show, agradeço pelo feedback! Vou consertar isso 👍🏼

Em qui., 12 de out. de 2023 às 11:28, Diego Ramiro ***@***.***>
escreveu:

**Comment by Diego-Girao** [comment]
Curti pois ficou diferente do que a galera tem feito por ai de portfólio, parabéns !!!!
